### ISSUE TITLE
remote.FulfillRequest problem

### ISSUE THREAD

**Issue by daivishooker** [raff/godet#59] opened 2023-06-18 15:22 UTC
when i want to use remote.EnableRequestPaused(true, godet.FetchRequestPattern{UrlPattern: "*", RequestStage: godet.RequestStageResponse}, godet.FetchRequestPattern{UrlPattern: "*", RequestStage: godet.RequestStageRequest}) and to pause the response 

after i use 		
data, _ := remote.FetchResponseBody(requestId) get the response and try to modify the body and then i use
remote.FulfillRequest(requestId, 200, "", ni, []byte(base64.StdEncoding.EncodeToString(data))) 

it look like the request unable to sent .evern i use the right headers

**Comment by raff** [comment] 2023-06-19 23:33
I am not sure I understand your issue and/or what you are tying to do.

If you set RequestStageRequest, the request will pause before being sent, then you need to resume it (I think with a call to remote.ContinueRequest.

When the request pauses again (on the response) you can call the FetchResponseBody and FullfillRequest.

Note that you need to setup a callback for the event "Fetch.requestPaused" in order to catch those events.
Also, if you don't need to make any modification to the outgoing request, I would suggest to not add a pattern for RequestStageRequest so the only event you are going to receive is for the response.

**Comment by daivishooker** [comment] 2023-06-20 07:14
remote.CallbackEvent("Fetch.requestPaused", func(params godet.Params) {

		var postData string
		requestId := params["requestId"].(string)
		if params["request"].(map[string]interface{})["postData"] != nil {
			postData = params["request"].(map[string]interface{})["postData"].(string)
		}
		url := params["request"].(map[string]interface{})["url"].(string)
		headers := make(map[string]string, 0)
		if _, ok := params["responseStatusCode"]; ok {
			data, _ := remote.FetchResponseBody(requestId)
			for _, _map := range params["responseHeaders"].([]interface{}) {
				m := _map.(map[string]interface{})
				headers[m["name"].(string)] = m["value"].(string)
				}
			}
			remote.FulfillRequest(requestId, 200, "ok", headers, []byte(base64.StdEncoding.EncodeToString(data)))
			return
		}
}


i want to modity the response .is this code wrong ?

**Comment by daivishooker** [comment] 2023-06-20 07:18
remote.CallbackEvent("Fetch.requestPaused", func(params godet.Params){
	if _, ok := params["responseStatusCode"]; ok {
			data, _ := remote.FetchResponseBody(requestId)
			remote.FulfillRequest(requestId, 200, "ok", nil, []byte(base64.StdEncoding.EncodeToString(data)))
			return
		} else {
			remote.ContinueRequest(requestId, "", "", "", nil)
			return
	}
}  also doesnt work

**Comment by raff** [comment] 2023-06-20 23:11
Ok, the following code does work:

`

    package main

    import (
            "bytes"
            "fmt"
            "time"

            "github.com/raff/godet"
    )

    func main() {
            // connect to Chrome instance
            remote, err := godet.Connect("localhost:9222", false)
            if err != nil {
                    fmt.Println(err)
                    return
            }

            // disconnect when done
            defer remote.Close()

            // get browser and protocol version
            version, _ := remote.Version()
            fmt.Println("Version", version)

            // install some callbacks
            remote.CallbackEvent(godet.EventClosed, func(params godet.Params) {
                    fmt.Println("RemoteDebugger connection terminated.")
            })

            remote.CallbackEvent("Network.requestWillBeSent", func(params godet.Params) {
                    fmt.Println("requestWillBeSent",
                            params["type"],
                            params["documentURL"],
                            params["request"].(map[string]any)["url"])
            })

            remote.CallbackEvent("Network.responseReceived", func(params godet.Params) {
                    fmt.Println("responseReceived",
                            params["type"],
                            params["response"].(map[string]any)["url"])
            })

            remote.CallbackEvent("Log.entryAdded", func(params godet.Params) {
                    entry := params["entry"].(map[string]any)
                    fmt.Println("LOG", entry["type"], entry["level"], entry["text"])
            })

            remote.CallbackEvent("Fetch.requestPaused", func(params godet.Params) {
                    url := params["request"].(map[string]any)["url"].(string)
                    requestId := params["requestId"].(string)

                    fmt.Println("REQUEST PAUSED:", url)

                    headers := map[string]string{}

                    if status, ok := params["responseStatusCode"]; ok {
                            fmt.Println(url, "response status:", status)

                            data, err := remote.FetchResponseBody(requestId)
                            if err != nil {
                                    fmt.Println("failed to fetch response:", err)
                                    return
                            }

                            /*
                                                    for _, _map := range params["responseHeaders"].([]any) {
                                                            m := _map.(map[string]any)
                                                            headers[m["name"].(string)] = m["value"].(string)
                                                    }
                            */

                            data = bytes.ReplaceAll(data, []byte("Mozilla"), []byte("Gopherilla"))

                            fmt.Println("FULLFILL with", string(data))

                            statusCode := int(status.(float64))
                            if err := remote.FulfillRequest(requestId, statusCode, "ok", headers, data); err != nil {
                                fmt.Println("failed to fullfill:", err)
                            }
                    } else {
                            fmt.Println("params", params)

                            fmt.Println("CONTINUE")
                            remote.ContinueRequest(requestId, "", "", "", nil)
                    }
            })

            // enable event processing
            remote.RuntimeEvents(true)
            remote.NetworkEvents(true)
            remote.PageEvents(true)
            remote.DOMEvents(true)
            remote.LogEvents(true)
            remote.EnableRequestPaused(true, godet.FetchRequestPattern{RequestStage: godet.RequestStageResponse})

            remote.Navigate("https://httpbin.org/get")

            time.Sleep(time.Hour)
    }
`

I think the issue is that I am passing the headers wrong. They should be sent in the same format they are received (an array of name/value maps) but currently I am sending a map of strings.

I will get that fixed, but if you don't need to "fix" the headers, this should work for now.

**Comment by raff** [comment] 2023-06-21 00:45
Fixed, if this solves your problem please close the issue.

**Comment by daivishooker** [comment] 2023-06-21 07:04
thx !!!!!!

**Closed as completed** 2023-06-21 07:04 UTC
